### ISSUE TITLE
Add list of tools that support SSP

### ISSUE THREAD

**Issue by JochenKoehler** [modelica/ssp-standard.org#3]
There is already a document that is not publicly available, i think it's on ssp-standard.dev

**Comment by chrbertsch** [comment]
Is this known: https://open-simulation-platform.github.io/ ?
“The structure of the co-simulated system can be defined using the System Structure & Parameterization standard (SSP)”

**Comment by JochenKoehler** [comment]
Hi Christian,



thanks for the information. There is also a member of the open-simulation-platform part of the SSP project.



Best regards

Jochen



Von: Christian Bertsch <notifications@github.com>
Gesendet: Dienstag, 9. Juni 2020 19:21
An: modelica/ssp-standard.org <ssp-standard.org@noreply.github.com>
Cc: Koehler Jochen FRD DIYV1 <jochen.koehler@zf.com>; Assign <assign@noreply.github.com>
Betreff: Re: [modelica/ssp-standard.org] Add list of tools that support SSP (#3)



Is this known: https://open-simulation-platform.github.io/ ?
“The structure of the co-simulated system can be defined using the System Structure & Parameterization standard (SSP)”

**Comment by markaren** [comment]
As one of the implementers, I can confirm that _libcosim_ (OSP) has basic support for SSP. Some features are missing though, e.g. unit conversions.

**Comment by markaren** [comment]
I recently developed [sspgen](https://github.com/NTNU-IHB/sspgen), which is a tool for generating `.ssp` archives using a simplified DSL. Among other things, it will perform simple validation of the specified content. Don't know a more suited channel for introducing this tool, which I believe could be beneficial for SSP users.

**Comment by chrbertsch** [comment]
>  Don't know a more suited channel for introducing this tool, which I believe could be beneficial for SSP users.

@markaren, @JochenKoehler : Shouldn's we add libcosim and sspgen to https://github.com/modelica/ssp-standard-dev/blob/master/Compatibility/ListOfCompatibleTools.md?
From my experience with FMI, open source imeplementations boost the adoption of a standard.

further ideas for distributing such information: 
@traversaro : what about "Awesome SSP"? 
@johanrhodin: do you have an idea how to spread such information?

**Comment by traversaro** [comment]
> @traversaro : what about "Awesome SSP"?

The original plan was for awesome-fmi to also host links to ssp-related tools, but for sure an ssp-dedicated repo would be better for visibility, I think I can prepare it.

**Comment by traversaro** [comment]
> 
> 
> > @traversaro : what about "Awesome SSP"?
> 
> The original plan was for awesome-fmi to also host links to ssp-related tools, but for sure an ssp-dedicated repo would be better for visibility, I think I can prepare it.

By the way, looking at the tools already listed in awesome-fmi for which it is mentioned at least basic SSP support there are: 
* fmpy (see https://github.com/CATIA-Systems/FMPy/tree/master/fmpy/ssp)
* FMIGo! (see https://www.fmigo.net/#ssp)

**Comment by GallLeo** [comment]
Initial list is now online, see Pull Request #5.

Before closing this ticket, SSP project should check the completeness of the list.
E.g. @markaren mentioned the following tools in #5:

```
libcosim,https://github.com/open-simulation-platform/libcosim,Open Simulation Platform,https://open-simulation-platform.github.io/,FMI based co-simulation library,Free,Yes,No"1.0"

Vico,https://github.com/NTNU-IHB/Vico,NTNU Ålesund,http://org.ntnu.no/intelligentsystemslab/,ECS based co-simulation framework with FMI and SSP support,Free,Yes,No"1.0"

sspgen,https://github.com/NTNU-IHB/sspgen,NTNU Ålesund,http://org.ntnu.no/intelligentsystemslab/,Command Line Application for generating SSP archives using a Kotlin DSL,Free,No,Yes"1.0"
```

**Comment by chrbertsch** [comment]
When will the tools list get updated with the tools mentioned above (and others?)

**Comment by MABackoffice** [comment]
@markaren Could you please check if your provided tools list of this is still up to date?
If yes, we should bring it up, soon.

**Comment by markaren** [comment]
Yes, still up to date. However, (while functional) Vico may be a little to experimental/unstable to be included in the official list (I'm the author).
So only adding: 

```
libcosim,https://github.com/open-simulation-platform/libcosim,Open Simulation Platform,https://open-simulation-platform.github.io/,FMI based co-simulation library,Free,Yes,No"1.0"

sspgen,https://github.com/NTNU-IHB/sspgen,NTNU Ålesund,http://org.ntnu.no/intelligentsystemslab/,Command Line Application for generating SSP archives using a Kotlin DSL,Free,No,Yes"1.0"
```

should be fine.
