### ISSUE TITLE
Change FMI to SSP logo in Website Code

### ISSUE THREAD

**Issue by chrbertsch** [modelica/ssp-standard.org#8]
There is an FMI logo hideden in the SSP website code:

`<meta property="og:image" content="http://ssp-standard.org/assets/img/fmi-logo.png">`

This leads e.g. when citing the link in Teams to an FMI logo instead of an SSP logo

![grafik](https://user-images.githubusercontent.com/16363372/158577480-8d687997-e5ea-491e-9c28-265dfa478a52.png)

Seems to be a copy-paste error when copying the webisite from FMI :-)

**Comment by JochenKoehler** [comment]
@chrbertsch Can you specify the file?

**Comment by GallLeo** [comment]
Found the wrong link in 
https://github.com/modelica/ssp-standard.org/blob/master/_includes/head.html

Fixed in 
https://github.com/modelica/ssp-standard.org/commit/e4c1634eae5966762ef2ba02e14bd0b501b9ff24

@chrbertsch or @JochenKoehler Please check and close.
